[SC-55] clean up zipdeploy v2

diff --git a/zipdeploy_v2/action.yaml b/zipdeploy_v2/action.yaml
--- a/zipdeploy_v2/action.yaml
+++ b/zipdeploy_v2/action.yaml
@@ -4,14 +4,10 @@ inputs:
   app-name:
     description: 'The Azure resource name of the app service to deploy to.'
     required: true
-  package-location:
-    description: 'The relative path to the zip package to deploy, if not in the current directory. Do not include the trailing slash.'
+  package-filename:
+    description: 'The relative path/filename to the zip package to deploy, if not in the current directory. Do not include the trailing slash.'
     required: false
-    default: '.'
-  package-name:
-    description: 'The name of the zip package to deploy'
-    required: false
-    default: ${{ inputs.app-name }}
+    default: './package.zip'
 runs:
   using: "composite"
   steps:
@@ -19,15 +15,15 @@ runs:
     shell: bash
     run: |
       APP_NAME=${{ inputs.app-name }}
-      PACKAGE_LOCATION=${{ inputs.package-location }}
-      PACKAGE_NAME=${{ inputs.app-name }}
+      PACKAGE_NAME=${{ inputs.package-filename }}
       token=$(curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com' -H Metadata:true -s | jq -r .access_token)
       subscriptions=$(curl -X GET https://management.azure.com/subscriptions?api-version=2020-01-01 -H "Authorization: Bearer $token" | jq  -r '.value[].subscriptionId')
       for sub in $subscriptions; do
-        app_id=$(curl -X GET "https://management.azure.com/subscriptions/$sub/resources?api-version=2021-04-01" -H "Authorization: Bearer $token" -H "Content-Type: application/json" | jq -r '.value[] | select(.name=="${{ inputs.app-name }}" and .type=="Microsoft.Web/sites") | .id')
+        app_id=$(curl -X GET "https://management.azure.com/subscriptions/$sub/resources?api-version=2021-04-01" -H "Authorization: Bearer $token" -H "Content-Type: application/json" | jq -r ".value[] | select(.name==\"${APP_NAME}\" and .type==\"Microsoft.Web/sites\") | .id")
         if [[ $app_id != "" ]]; then break; fi
       done
+      if [[ $app_id != "" ]]; then echo "error: app not found"; exit 1; fi
       publishInfo=$(curl -X POST https://management.azure.com${app_id}/config/publishingcredentials/list?api-version=2019-08-01 -H "Authorization: Bearer $token" -H "Content-Type: application/json" -H "Content-Length: 0")
       publishName=$(jq -r '.properties.publishingUserName' <<<$publishInfo)
       publishPass=$(jq -r '.properties.publishingPassword' <<<$publishInfo)
-      curl -XPOST --fail -u "$publishName:$publishPass" --data-binary @"${{ inputs.package-location }}/${{ inputs.package-name }}.zip" "https://${{ inputs.app-name }}.scm.azurewebsites.net/api/zipdeploy"
+      curl -XPOST --fail -u "$publishName:$publishPass" --data-binary @"${{ inputs.package-filename }}.zip" "https://${{ inputs.app-name }}.scm.azurewebsites.net/api/zipdeploy"
